### ISSUE TITLE
Comparing the memory footprint of pelikan and redis

### ISSUE THREAD

**Issue by skimhugo** [pelikan-io/pelikan#127]
The question is pelikan seems preallocate a large chunk of memory, how can I make a better comparison?

I saw the crate segcache‘s code logic, to use segcache also need preallocate memory.

I'm confused, how do I compare pelikan with other hash-map solution.

**Comment by thinkingfish** [comment]
In segcache, the number of segments not in use is tracked by metrics: `SEGMENT_FREE`, which started out as the total number of segments pre-allocated. It's decremented [here](https://github.com/pelikan-io/pelikan/blob/main/src/storage/segcache/src/segments/segments.rs#L429). If you use `segment_size` in the config and this metric, you can calculate how much memory is preallocated by not in use.

**Comment by skimhugo** [comment]
Thanks, I will try.
