### ISSUE TITLE
Resp protocol parser crashes when given a command ending with a newline

### ISSUE THREAD

**Issue by swlynch99** [pelikan-io/pelikan#40]
To reproduce,
1. Start a pelikan resp service somehow (e.g. momento proxy)
2. Run `netcat` to connect to the resp port and type out 
   ```
   GET test<enter>
   ```

This will cause pelikan to panic and crash. The root cause is this line here: https://github.com/pelikan-io/pelikan/blob/main/src/protocol/resp/src/request/mod.rs#L89

**Comment by hderms** [comment]
I will fix this shortly
